### ISSUE TITLE
Grid regenerates in spawn chunks after server restart

### ISSUE THREAD

**Issue by DaBomb42** [DavidS-Repo/SkyGridx#4]
Every time I restart the server, skygrid blocks get replaced and randomized within the spawn chunks. Chunks outside spawn are unaffected. 

Not sure if this is an issue or if I am doing something wrong.

**Comment by DavidS-Repo** [comment]
That issue should be fixed in the newest version of the plugin. I can't recreate the issue on my own server (running Paper) after my attempts to restart and reload. Can you confirm you have the newest version of the plugin?

If you are running the newest version and still getting the issue, it's possible that there might be some specific configuration or setup on your end that's causing this behavior. Could you provide more details about your server environment, such as any additional plugins you're using or any custom configurations?

**Comment by DavidS-Repo** [comment]
Issue fixed in news version.
