### ISSUE TITLE
Block height limit

### ISSUE THREAD

**Issue by CorentinStauder** [DavidS-Repo/SkyGridx#6]
Hello,

I've notice the height limit of blocks seems to be hard coded. Is there any purpose of this ? (performance issues, datapack incompatibility).

I suggest to add this as a configurable feature of config file

**Comment by DavidS-Repo** [comment]
Hello @CorentinStauder,

I initially limited the height due to performance issues in earlier versions of the plugin. However, with recent updates, the performance of the generator has significantly improved thanks to the use of more efficient data structures and faster lookup times.

As mentioned in [issue #5](https://github.com/DavidS-Repo/SkyGridx/issues/5), I am releasing a new settings file on Wednesday. This update will allow you to configure the minimum and maximum height for block placement in each world, along with other generator settings.


Best,
David

**Comment by DavidS-Repo** [comment]
Implemented settings file to add customizable grid height for all environments, it can be found in the plugin folder after boot.

The updated version of the jar is available in the [main page](https://github.com/DavidS-Repo/SkyGridx).
[SkyGrid.jar](https://github.com/DavidS-Repo/SkyGridx/blob/main/SkyGrid.jar) or here directly.

**Comment by CorentinStauder** [comment]
That's again perfect and working great ! Thanks for your work !
